'use client';

import { MarkdownContent } from '@/components/MarkdownContent';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Sparkles } from 'lucide-react';

interface ProposalDescriptionProps {
  aiSummary: string | null;
  abstract: string | null;
}

export function ProposalDescription({ aiSummary, abstract }: ProposalDescriptionProps) {
  if (!aiSummary && !abstract) return null;

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-base">{aiSummary ? 'Description' : 'Description'}</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {aiSummary && (
          <div className="bg-primary/5 border-l-2 border-primary/40 rounded-r-lg p-3">
            <div className="flex items-center gap-1.5 mb-1.5">
              <Sparkles className="h-3.5 w-3.5 text-primary" />
              <span className="text-xs font-semibold text-primary">AI Summary</span>
            </div>
            <MarkdownContent content={aiSummary} className="text-sm leading-relaxed" />
            <p className="text-[10px] text-muted-foreground mt-2">
              Generated by AI — may not capture all details
            </p>
          </div>
        )}
        {abstract && (
          <div>
            {aiSummary && (
              <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">
                Full Description
              </p>
            )}
            <MarkdownContent
              content={abstract}
              className="text-sm text-foreground/85 leading-relaxed"
            />
          </div>
        )}
      </CardContent>
    </Card>
  );
}
