/**
 * Proposal Brief — AI-synthesized intelligence product for a governance proposal.
 *
 * Pattern: template-first, AI-enhanced (same as lib/narratives.ts).
 * Assembles all available context → generates structured JSON brief → stores in DB.
 *
 * Briefs are generated by Inngest background jobs, NOT on-demand during page load.
 * The page reads from the DB cache; the API triggers regeneration if stale.
 */

import { createClient, getSupabaseAdmin } from '@/lib/supabase';
import { createHash } from 'crypto';
import { logger } from '@/lib/logger';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface CitedDRep {
  drepId: string;
  name: string | null;
  vote: 'Yes' | 'No' | 'Abstain';
}

export interface BriefSection {
  key: string;
  title: string;
  content: string;
  citedDReps?: CitedDRep[];
}

export interface ProposalBriefContent {
  debateStatus: string;
  sections: BriefSection[];
  generatedAt: string;
}

export interface ProposalBriefRow {
  id: string;
  proposalTxHash: string;
  proposalIndex: number;
  content: ProposalBriefContent;
  convictionScore: number;
  polarizationScore: number;
  rationaleHash: string | null;
  rationaleCount: number;
  helpfulCount: number;
  notHelpfulCount: number;
  modelUsed: string | null;
  generationTimeMs: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface RationaleForBrief {
  drepId: string;
  drepName: string | null;
  vote: 'Yes' | 'No' | 'Abstain';
  rationaleText: string | null;
  rationaleAiSummary: string | null;
  qualityScore?: number | null;
}

export interface BriefGenerationInput {
  txHash: string;
  proposalIndex: number;
  title: string | null;
  abstract: string | null;
  proposalType: string;
  withdrawalAmount: number | null;
  aiSummary: string | null;
  rationales: RationaleForBrief[];
  yesCount: number;
  noCount: number;
  abstainCount: number;
  convictionScore: number;
  polarizationScore: number;
  citizenSentiment: number | null;
  concernFlags: string[];
  constitutionalArticles: string[];
  historicalContext: string | null;
}

// ---------------------------------------------------------------------------
// Rationale hash — for staleness detection
// ---------------------------------------------------------------------------

export function computeRationaleHash(rationales: RationaleForBrief[]): string {
  const sorted = rationales
    .map((r) => r.drepId)
    .sort()
    .join(',');
  return createHash('sha256').update(sorted).digest('hex').slice(0, 16);
}

export function isBriefStale(existing: ProposalBriefRow, currentHash: string): boolean {
  return existing.rationaleHash !== currentHash;
}

// ---------------------------------------------------------------------------
// Database operations
// ---------------------------------------------------------------------------

export async function getProposalBrief(
  txHash: string,
  proposalIndex: number,
): Promise<ProposalBriefRow | null> {
  try {
    const supabase = createClient();
    const { data, error } = await supabase
      .from('proposal_briefs')
      .select('*')
      .eq('proposal_tx_hash', txHash)
      .eq('proposal_index', proposalIndex)
      .single();

    if (error || !data) return null;

    return {
      id: data.id,
      proposalTxHash: data.proposal_tx_hash,
      proposalIndex: data.proposal_index,
      content: data.content as unknown as ProposalBriefContent,
      convictionScore: data.conviction_score,
      polarizationScore: data.polarization_score,
      rationaleHash: data.rationale_hash,
      rationaleCount: data.rationale_count,
      helpfulCount: data.helpful_count,
      notHelpfulCount: data.not_helpful_count,
      modelUsed: data.model_used,
      generationTimeMs: data.generation_time_ms,
      createdAt: data.created_at,
      updatedAt: data.updated_at,
    };
  } catch (err) {
    logger.error('[ProposalBrief] Failed to fetch brief', { txHash, error: err });
    return null;
  }
}

export async function storeProposalBrief(
  txHash: string,
  proposalIndex: number,
  content: ProposalBriefContent,
  conviction: number,
  polarization: number,
  rationaleHash: string,
  rationaleCount: number,
  modelUsed: string | null,
  generationTimeMs: number | null,
): Promise<void> {
  try {
    const supabase = getSupabaseAdmin();
    const { error } = await supabase.from('proposal_briefs').upsert(
      {
        proposal_tx_hash: txHash,
        proposal_index: proposalIndex,
        content: content as unknown as Record<string, unknown>,
        conviction_score: conviction,
        polarization_score: polarization,
        rationale_hash: rationaleHash,
        rationale_count: rationaleCount,
        model_used: modelUsed,
        generation_time_ms: generationTimeMs,
        updated_at: new Date().toISOString(),
      },
      { onConflict: 'proposal_tx_hash,proposal_index' },
    );

    if (error) {
      logger.error('[ProposalBrief] Failed to store brief', { txHash, error: error.message });
    }
  } catch (err) {
    logger.error('[ProposalBrief] Unexpected error storing brief', { txHash, error: err });
  }
}

export async function submitBriefFeedback(
  briefId: string,
  userId: string,
  helpful: boolean,
): Promise<boolean> {
  try {
    const supabase = getSupabaseAdmin();

    // Upsert feedback
    const { error: fbError } = await supabase
      .from('proposal_brief_feedback')
      .upsert({ brief_id: briefId, user_id: userId, helpful }, { onConflict: 'brief_id,user_id' });

    if (fbError) {
      logger.error('[ProposalBrief] Feedback upsert failed', { error: fbError.message });
      return false;
    }

    // Update counts on the brief
    const { data: counts } = await supabase
      .from('proposal_brief_feedback')
      .select('helpful')
      .eq('brief_id', briefId);

    if (counts) {
      const helpfulCount = counts.filter((c) => c.helpful).length;
      const notHelpfulCount = counts.filter((c) => !c.helpful).length;

      await supabase
        .from('proposal_briefs')
        .update({ helpful_count: helpfulCount, not_helpful_count: notHelpfulCount })
        .eq('id', briefId);
    }

    return true;
  } catch (err) {
    logger.error('[ProposalBrief] Feedback error', { error: err });
    return false;
  }
}

// ---------------------------------------------------------------------------
// Context assembly
// ---------------------------------------------------------------------------

export async function assembleProposalBriefInput(
  txHash: string,
  proposalIndex: number,
): Promise<BriefGenerationInput | null> {
  try {
    const { getProposalByKey, getVotesByProposal } = await import('@/lib/data');
    const { getRelevantArticles } = await import('@/lib/constitution');
    const { computeConviction, computePolarization } = await import('@/lib/convictionPulse');

    const [proposal, votes] = await Promise.all([
      getProposalByKey(txHash, proposalIndex),
      getVotesByProposal(txHash, proposalIndex),
    ]);

    if (!proposal) return null;

    const rationales: RationaleForBrief[] = votes
      .filter((v) => v.rationaleAiSummary || v.rationaleText)
      .map((v) => ({
        drepId: v.drepId,
        drepName: v.drepName,
        vote: v.vote,
        rationaleText: v.rationaleText,
        rationaleAiSummary: v.rationaleAiSummary,
      }));

    // Compute conviction + polarization
    const votesForPulse = votes.map((v) => ({
      drepId: v.drepId,
      drepName: v.drepName,
      vote: v.vote,
      votingPowerLovelace: null as number | null, // Power data not in vote detail
      hasRationale: !!(v.rationaleAiSummary || v.rationaleText),
    }));

    const conviction = computeConviction(votesForPulse);
    const polarization = computePolarization(votesForPulse);

    // Constitutional articles
    const articles = getRelevantArticles(proposal.proposalType);

    // Concern flags from engagement signals (best-effort)
    let concernFlags: string[] = [];
    try {
      const supabase = createClient();
      const { data: concerns } = await supabase
        .from('concern_flags')
        .select('concern_type')
        .eq('proposal_tx_hash', txHash)
        .eq('proposal_index', proposalIndex)
        .gt('flag_count', 2);
      if (concerns) {
        concernFlags = concerns.map((c) => c.concern_type as string);
      }
    } catch {
      // Non-critical
    }

    // Historical context for treasury proposals
    let historicalContext: string | null = null;
    if (proposal.proposalType === 'TreasuryWithdrawals' && proposal.withdrawalAmount) {
      try {
        const { getProposalHistoricalContext } = await import('@/lib/proposalContext');
        const ctx = await getProposalHistoricalContext(txHash, proposalIndex);
        if (ctx) {
          const amtAda = proposal.withdrawalAmount! / 1_000_000;
          historicalContext = `This withdrawal of ${amtAda.toLocaleString()} ADA is at the ${Math.round(ctx.amountPercentile)}th percentile of treasury requests (median: ${ctx.medianWithdrawalAda.toLocaleString()} ADA across ${ctx.totalTreasuryProposals} proposals).`;
        }
      } catch {
        // Non-critical
      }
    }

    // Citizen sentiment (best-effort)
    let citizenSentiment: number | null = null;
    try {
      const supabase = createClient();
      const { data: signals } = await supabase
        .from('engagement_signals')
        .select('signal_value')
        .eq('entity_type', 'proposal')
        .eq('entity_id', `${txHash}:${proposalIndex}`)
        .eq('signal_type', 'sentiment');
      if (signals && signals.length > 0) {
        const avg = signals.reduce((s, r) => s + (r.signal_value as number), 0) / signals.length;
        citizenSentiment = Math.round(avg);
      }
    } catch {
      // Non-critical
    }

    return {
      txHash,
      proposalIndex,
      title: proposal.title,
      abstract: proposal.abstract,
      proposalType: proposal.proposalType,
      withdrawalAmount: proposal.withdrawalAmount,
      aiSummary: proposal.aiSummary,
      rationales,
      yesCount: proposal.yesCount,
      noCount: proposal.noCount,
      abstainCount: proposal.abstainCount,
      convictionScore: conviction,
      polarizationScore: polarization,
      citizenSentiment,
      concernFlags,
      constitutionalArticles: articles.map((a) => `${a.id}: ${a.text}`),
      historicalContext,
    };
  } catch (err) {
    logger.error('[ProposalBrief] Context assembly failed', { txHash, error: err });
    return null;
  }
}

// ---------------------------------------------------------------------------
// AI Brief Generation
// ---------------------------------------------------------------------------

export async function generateProposalBrief(
  input: BriefGenerationInput,
): Promise<ProposalBriefContent> {
  // Require minimum 3 rationales for AI generation
  if (input.rationales.length < 3) {
    return generateTemplateBrief(input);
  }

  try {
    const { generateJSON } = await import('@/lib/ai');

    const system = `You are a governance intelligence analyst for Cardano. Your job is to synthesize DRep voting rationales into a clear, balanced intelligence brief.

Rules:
- Conclusions first, then evidence
- Cite DReps by name when attributing arguments
- 2-4 sentences per section maximum
- Never take sides — present the strongest version of each position
- Use plain language, no jargon
- If rationales are thin, say so honestly
- Return valid JSON matching the schema exactly`;

    const yesRationales = input.rationales
      .filter((r) => r.vote === 'Yes')
      .map(
        (r) =>
          `  - ${r.drepName || r.drepId.slice(0, 12)}: ${r.rationaleAiSummary || r.rationaleText?.slice(0, 300)}`,
      )
      .join('\n');

    const noRationales = input.rationales
      .filter((r) => r.vote === 'No')
      .map(
        (r) =>
          `  - ${r.drepName || r.drepId.slice(0, 12)}: ${r.rationaleAiSummary || r.rationaleText?.slice(0, 300)}`,
      )
      .join('\n');

    const abstainRationales = input.rationales
      .filter((r) => r.vote === 'Abstain')
      .map(
        (r) =>
          `  - ${r.drepName || r.drepId.slice(0, 12)}: ${r.rationaleAiSummary || r.rationaleText?.slice(0, 300)}`,
      )
      .join('\n');

    const prompt = `Analyze this Cardano governance proposal and generate an intelligence brief.

## Proposal
Title: ${input.title || 'Untitled'}
Type: ${input.proposalType}
${input.withdrawalAmount ? `Treasury Request: ${(input.withdrawalAmount / 1_000_000).toLocaleString()} ADA` : ''}
${input.abstract ? `Abstract: ${input.abstract.slice(0, 500)}` : ''}
${input.aiSummary ? `AI Summary: ${input.aiSummary}` : ''}

## Vote Tally
Yes: ${input.yesCount} | No: ${input.noCount} | Abstain: ${input.abstainCount}
Conviction: ${input.convictionScore}/100 | Polarization: ${input.polarizationScore}/100

## Rationales — FOR (${input.rationales.filter((r) => r.vote === 'Yes').length})
${yesRationales || '  (none provided)'}

## Rationales — AGAINST (${input.rationales.filter((r) => r.vote === 'No').length})
${noRationales || '  (none provided)'}

## Rationales — ABSTAIN (${input.rationales.filter((r) => r.vote === 'Abstain').length})
${abstainRationales || '  (none provided)'}

${input.citizenSentiment != null ? `## Citizen Sentiment: ${input.citizenSentiment}/100` : ''}
${input.concernFlags.length > 0 ? `## Community Concerns: ${input.concernFlags.join(', ')}` : ''}
${input.historicalContext ? `## Historical Context: ${input.historicalContext}` : ''}
${input.constitutionalArticles.length > 0 ? `## Relevant Constitutional Articles:\n${input.constitutionalArticles.map((a) => `  - ${a}`).join('\n')}` : ''}

Return JSON with this exact structure:
{
  "debateStatus": "one sentence summarizing where the debate stands",
  "sections": [
    {
      "key": "what_this_proposes",
      "title": "What This Proposes",
      "content": "2-3 sentences explaining the proposal in plain language"
    },
    {
      "key": "the_case_for",
      "title": "The Case For",
      "content": "2-4 sentences synthesizing the strongest arguments in favor",
      "citedDReps": [{"drepId": "...", "name": "...", "vote": "Yes"}]
    },
    {
      "key": "the_case_against",
      "title": "The Case Against",
      "content": "2-4 sentences synthesizing the strongest arguments against",
      "citedDReps": [{"drepId": "...", "name": "...", "vote": "No"}]
    },
    {
      "key": "the_common_ground",
      "title": "Common Ground",
      "content": "1-3 sentences on what both sides agree on, or shared concerns"
    },
    {
      "key": "community_temperature",
      "title": "Community Temperature",
      "content": "1-2 sentences on overall engagement, conviction, and citizen sentiment"
    }
  ]
}`;

    const result = await generateJSON<{
      debateStatus: string;
      sections: Array<{
        key: string;
        title: string;
        content: string;
        citedDReps?: Array<{ drepId: string; name: string | null; vote: string }>;
      }>;
    }>(prompt, {
      system,
      model: 'FAST',
      maxTokens: 2048,
      temperature: 0.3,
    });

    if (result && result.sections && result.sections.length > 0) {
      return {
        debateStatus: result.debateStatus,
        sections: result.sections.map((s) => ({
          key: s.key,
          title: s.title,
          content: s.content,
          citedDReps: s.citedDReps?.map((d) => ({
            drepId: d.drepId,
            name: d.name,
            vote: d.vote as 'Yes' | 'No' | 'Abstain',
          })),
        })),
        generatedAt: new Date().toISOString(),
      };
    }
  } catch (err) {
    logger.error('[ProposalBrief] AI generation failed, falling back to template', { error: err });
  }

  return generateTemplateBrief(input);
}

// ---------------------------------------------------------------------------
// Template fallback (no AI)
// ---------------------------------------------------------------------------

export function generateTemplateBrief(input: BriefGenerationInput): ProposalBriefContent {
  const sections: BriefSection[] = [];

  // What this proposes
  const proposalDesc =
    input.aiSummary || input.abstract?.slice(0, 300) || 'No description available.';
  sections.push({
    key: 'what_this_proposes',
    title: 'What This Proposes',
    content: proposalDesc,
  });

  // Vote summary as case for/against
  const total = input.yesCount + input.noCount + input.abstainCount;
  if (total > 0) {
    const yesPct = Math.round((input.yesCount / total) * 100);
    const noPct = Math.round((input.noCount / total) * 100);

    if (input.yesCount > 0) {
      const yesCited = input.rationales
        .filter((r) => r.vote === 'Yes')
        .slice(0, 3)
        .map((r) => ({
          drepId: r.drepId,
          name: r.drepName,
          vote: 'Yes' as const,
        }));
      const yesReasons = input.rationales
        .filter((r) => r.vote === 'Yes')
        .slice(0, 2)
        .map((r) => r.rationaleAiSummary || r.rationaleText?.slice(0, 150))
        .filter(Boolean);

      sections.push({
        key: 'the_case_for',
        title: 'The Case For',
        content:
          yesReasons.length > 0
            ? `${yesPct}% of voters support this proposal. Key arguments: ${yesReasons.join('. ')}`
            : `${yesPct}% of voters (${input.yesCount}) voted Yes, though few provided detailed rationale.`,
        citedDReps: yesCited.length > 0 ? yesCited : undefined,
      });
    }

    if (input.noCount > 0) {
      const noCited = input.rationales
        .filter((r) => r.vote === 'No')
        .slice(0, 3)
        .map((r) => ({
          drepId: r.drepId,
          name: r.drepName,
          vote: 'No' as const,
        }));
      const noReasons = input.rationales
        .filter((r) => r.vote === 'No')
        .slice(0, 2)
        .map((r) => r.rationaleAiSummary || r.rationaleText?.slice(0, 150))
        .filter(Boolean);

      sections.push({
        key: 'the_case_against',
        title: 'The Case Against',
        content:
          noReasons.length > 0
            ? `${noPct}% voted against. Concerns include: ${noReasons.join('. ')}`
            : `${noPct}% of voters (${input.noCount}) voted No, though few provided detailed rationale.`,
        citedDReps: noCited.length > 0 ? noCited : undefined,
      });
    }
  }

  // Community temperature
  const tempParts: string[] = [];
  tempParts.push(`${total} DReps have voted.`);
  if (input.convictionScore > 0) {
    tempParts.push(`Conviction level: ${input.convictionScore}/100.`);
  }
  if (input.citizenSentiment != null) {
    tempParts.push(`Citizen sentiment: ${input.citizenSentiment}/100.`);
  }
  sections.push({
    key: 'community_temperature',
    title: 'Community Temperature',
    content: tempParts.join(' '),
  });

  const statusParts: string[] = [];
  if (total === 0) {
    statusParts.push('No votes have been cast yet.');
  } else {
    const leading = input.yesCount >= input.noCount ? 'Yes' : 'No';
    const margin = Math.abs(input.yesCount - input.noCount);
    statusParts.push(
      `${leading} leads by ${margin} vote${margin !== 1 ? 's' : ''} with ${total} total votes cast.`,
    );
  }

  return {
    debateStatus: statusParts.join(' '),
    sections,
    generatedAt: new Date().toISOString(),
  };
}
