'use client';

/**
 * AIProvenanceDiff — shows word-level diff between AI-generated text and
 * current draft text. The transparency selling point: "see exactly what
 * you changed from the AI draft."
 */

import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Bot } from 'lucide-react';
import { WordDiffField } from './VersionDiff';
import type { DraftAIMeta } from '@/lib/workspace/types';

interface AIProvenanceDiffProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  aiMeta: DraftAIMeta;
  currentText: {
    title: string;
    abstract: string;
    motivation: string;
    rationale: string;
  };
}

function computeEditPercent(original: string, current: string): number {
  if (!original && !current) return 0;
  if (original === current) return 0;
  const maxLen = Math.max(original.length, current.length);
  if (maxLen === 0) return 0;
  let changes = 0;
  const minLen = Math.min(original.length, current.length);
  for (let i = 0; i < minLen; i++) {
    if (original[i] !== current[i]) changes++;
  }
  changes += Math.abs(original.length - current.length);
  return Math.round((changes / maxLen) * 100);
}

const FIELDS = [
  { key: 'title' as const, label: 'Title' },
  { key: 'abstract' as const, label: 'Abstract' },
  { key: 'motivation' as const, label: 'Motivation' },
  { key: 'rationale' as const, label: 'Rationale' },
];

export function AIProvenanceDiff({
  open,
  onOpenChange,
  aiMeta,
  currentText,
}: AIProvenanceDiffProps) {
  const fieldsWithChanges = FIELDS.filter(
    ({ key }) =>
      aiMeta.fieldsGenerated.includes(key) && aiMeta.originalText[key] !== currentText[key],
  );

  const totalEditPercent = (() => {
    let totalOriginal = 0;
    let totalChanges = 0;
    for (const { key } of FIELDS) {
      if (!aiMeta.fieldsGenerated.includes(key)) continue;
      const orig = aiMeta.originalText[key];
      const curr = currentText[key];
      totalOriginal += orig.length;
      const maxLen = Math.max(orig.length, curr.length);
      if (maxLen === 0) continue;
      let changes = 0;
      const minLen = Math.min(orig.length, curr.length);
      for (let i = 0; i < minLen; i++) {
        if (orig[i] !== curr[i]) changes++;
      }
      changes += Math.abs(orig.length - curr.length);
      totalChanges += changes;
    }
    return totalOriginal > 0 ? Math.round((totalChanges / totalOriginal) * 100) : 0;
  })();

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-3xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Bot className="h-5 w-5 text-primary" />
            AI Draft vs Your Edits
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-1 text-sm">
          <p className="text-muted-foreground">
            Your proposal was generated by AI and you&apos;ve edited{' '}
            <span className="font-semibold text-foreground">{totalEditPercent}%</span> of the
            original text.{' '}
            {totalEditPercent === 0 ? 'No changes yet.' : 'Changes highlighted below.'}
          </p>
          <p className="text-xs text-muted-foreground">
            <span className="line-through text-rose-500">Red strikethrough</span> = AI original
            removed.{' '}
            <span className="bg-emerald-500/20 text-emerald-700 dark:text-emerald-300 rounded-sm px-0.5">
              Green highlight
            </span>{' '}
            = your addition.
          </p>
        </div>

        <div className="space-y-5 mt-2">
          {FIELDS.filter(({ key }) => aiMeta.fieldsGenerated.includes(key)).map(
            ({ key, label }) => {
              const editPct = computeEditPercent(aiMeta.originalText[key], currentText[key]);
              return (
                <div key={key} className="space-y-1.5">
                  <div className="flex items-center justify-between">
                    <h4 className="text-sm font-semibold">{label}</h4>
                    <span className="text-xs text-muted-foreground">
                      {editPct === 0 ? 'unchanged' : `${editPct}% edited`}
                    </span>
                  </div>
                  <WordDiffField oldText={aiMeta.originalText[key]} newText={currentText[key]} />
                </div>
              );
            },
          )}
        </div>

        {fieldsWithChanges.length === 0 && (
          <p className="text-sm text-muted-foreground text-center py-4">
            No edits to AI-generated text yet. Start editing to see your changes here.
          </p>
        )}
      </DialogContent>
    </Dialog>
  );
}
