ALTER TABLE feature_flags ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'Uncategorized';

UPDATE feature_flags SET category = 'Cross-Chain' WHERE key IN ('cross_chain_observatory', 'cross_chain_embed', 'cross_chain_sync');

INSERT INTO feature_flags (key, enabled, description, category) VALUES
  ('ai_proposal_explainer', true, 'On-demand Claude proposal explanations via Explain button', 'AI'),
  ('ai_narratives', true, 'AI-generated DRep profile narratives and governance briefs (falls back to template)', 'AI'),
  ('ai_state_of_governance', true, 'AI narrative in weekly State of Governance reports', 'AI'),
  ('ai_governance_brief', true, 'Weekly AI governance brief generation and GovernanceBriefCard', 'AI'),
  ('developer_platform', true, '/developers page and header nav link', 'Platform'),
  ('delegator_identity', true, 'DelegatorGovernanceCard on /governance and OG image', 'Platform'),
  ('embeddable_widgets', true, 'All /embed/* pages and embed.js script loader', 'Platform'),
  ('drep_qa', true, 'DRep-delegator Q&A channel in communication feed', 'Social'),
  ('social_proof', true, 'SocialProofBadge on DRep profiles and proposal detail', 'Social'),
  ('milestone_celebrations', true, 'Milestone celebration toast overlays on dashboard', 'Social'),
  ('delegation_ceremony', true, 'Enhanced identity-aware delegation ceremony modal', 'Social'),
  ('activity_feeds', true, 'Activity feeds on Pulse, Governance, DRep profiles, and homepage ticker', 'Social'),
  ('governance_health_index', true, 'GHI gauge and sparkline on Pulse and Homepage', 'Intelligence'),
  ('cross_proposal_insights', true, 'Cross-proposal insight cards on Pulse page', 'Intelligence'),
  ('state_of_governance_reports', true, 'State of Governance weekly reports and Pulse link', 'Intelligence'),
  ('narrative_summaries', true, 'NarrativeSummary text on Proposals, Pulse, Dashboard, DRep profiles', 'Narrative'),
  ('proposals_hero', true, 'ProposalsHero command-center hero on /proposals', 'Narrative'),
  ('governance_dna_quiz', true, 'Governance DNA Quiz on /discover with match reveals', 'Discovery'),
  ('drep_quick_view', true, 'DRepQuickView bottom/side sheet on discover', 'Discovery'),
  ('sentiment_polls', true, 'Sentiment polls on proposal detail pages', 'Discovery'),
  ('compare_page', true, '/compare page and CompareButton on profiles', 'Discovery'),
  ('representation_matching', true, 'Match percentage display and Best Match sort from quiz data', 'Discovery'),
  ('drep_authoring', true, 'VoteExplanationEditor, GovernancePhilosophyEditor, PositionStatementEditor', 'DRep Tools'),
  ('claim_experience', true, 'Enhanced claim page with FOMO treatment and ClaimCelebration', 'DRep Tools'),
  ('onboarding_checklist', true, 'Post-claim OnboardingChecklist on dashboard', 'DRep Tools'),
  ('watchlist', true, 'Watchlist intelligence and watchlist toggle on DRep cards', 'Governance'),
  ('governance_calendar', true, 'Governance calendar on /governance page', 'Governance'),
  ('citizen_levels', true, 'Governance citizen levels, progression, and CitizenProgressBar', 'Governance'),
  ('financial_impact', true, 'FinancialImpactCard on proposals and DRepTreasuryStance on profiles', 'Governance'),
  ('leaderboard', true, 'Leaderboard, Hall of Fame, and Movers on Pulse page', 'Governance'),
  ('treasury_intelligence', true, 'Treasury Simulator and Accountability tabs plus accountability polls', 'Treasury'),
  ('constellation_3d', true, 'R3F WebGL constellation on homepage (fallback: static gradient)', 'Visual'),
  ('score_simulator', true, 'Score Simulator on dashboard', 'Dashboard'),
  ('score_history', true, 'Score history chart on dashboard and DRep profile', 'Dashboard'),
  ('activity_heatmap', true, 'Activity heatmap on dashboard and DRep profile', 'Dashboard'),
  ('sharing_surfaces', true, 'Wrapped cards, delegator cards, epoch summaries, badge embeds', 'Sharing'),
  ('notifications', true, 'Automated notification generation via check-notifications Inngest', 'Notifications'),
  ('push_notifications', true, 'Push notification delivery channel', 'Notifications')
ON CONFLICT (key) DO NOTHING;
